version: '3.1'

services:
  backend:
    build: .
    restart: unless-stopped
    links:
      - mongo
    ports:
      - 8080:8080
    environment:
      MONGO_URI: mongodb://test:test1234@mongo:27017/testdb
  mongo:
    image: mongo:3.6.17
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_USERNAME: test
      MONGO_INITDB_PASSWORD: test1234
      MONGO_INITDB_DATABASE: testdb
    expose:
      - "27017"
    volumes:
      - ./data:/docker-entrypoint-initdb.d:ro
      - mongo_data:/data/db

volumes:
    mongo_data:
      driver: local
